# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hacker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackers.Hacker'),
        ),
    ]
