# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('message_id', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
