# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('school_identification', models.CharField(blank=True, max_length=50)),
                ('education_level', models.CharField(blank=True, choices=[('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Bachillerato', 'Bachillerato'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
                ('major', models.CharField(blank=True, max_length=80)),
                ('school_join_date', models.DateField(null=True)),
                ('school_graduation_date', models.DateField(null=True)),
                ('tshirt_size', models.CharField(blank=True, choices=[('Chica - Mujer', 'S-W'), ('Mediana - Mujer', 'M-W'), ('Grande - Mujer', 'L-W'), ('Extra Grande - Mujer', 'XL-W'), ('Chica - Hombre', 'S-M'), ('Mediana - Hombre', 'M-M'), ('Grande - Hombre', 'L-M'), ('Extra Grande - Hombre', 'XL-M')], max_length=60)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('first_time_hacker', models.BooleanField(default=True)),
                ('first_time_event', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackers.Campus')),
                ('event_participations', models.ManyToManyField(blank=True, to='hackers.EventEdition')),
                ('hackathons', models.ManyToManyField(blank=True, to='hackers.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hacker',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackers.School'),
        ),
        migrations.AddField(
            model_name='campus',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackers.School'),
        ),
    ]
