# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hacker',
            old_name='school_graduation_date',
            new_name='school_graduation_year',
        ),
        migrations.RenameField(
            model_name='hacker',
            old_name='school_join_date',
            new_name='school_join_year',
        ),
    ]
