# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
