# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0002_auto_20160822_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='event_participations',
            field=models.ManyToManyField(blank=True, to='hackers.EventEdition'),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='hackathons',
            field=models.ManyToManyField(blank=True, to='hackers.Hackathon'),
        ),
    ]
