# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0002_auto_20160824_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria'), ('Bachillerato', 'Bachillerato'), ('Universidad', 'Universidad'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20),
        ),
    ]
