# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0003_auto_20160831_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hacker',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
