# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0004_auto_20160908_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='currently_working',
            field=models.BooleanField(default=True),
        ),
    ]
